version: '3'
services:
  processing:
    image: "kaspa-merge-mining:latest"
    command:
      - "/app/processing"
      - "--connection-string=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable"
    network_mode: host
    restart: always
    volumes:
      - /Users/neo/Library/Application Support/Kgi-processing:/root/.kgi-processing/